### ISSUE TITLE
Corpus

### ISSUE THREAD

**Issue by kmurphy902** [jakelever/civicmine#1]
Hi Jake,
Quick question: You have four categories (diagnostic, predictive, predisposing, prognostic). Do you by any chance have any plans to classify the corpus with whether a relationship in a sentence is a true positive or false positive? OR, do you know of a corpus like this out in the interwebs?
Thanks,
KMS

**Comment by jakelever** [comment]
Hey, by true positive, do you mean an clinical biomarker (extracted from the text) that turned out to be likely correct when we delved further into the paper (or associated literature)? If so, not on a large scale.

**Comment by kmurphy902** [comment]
Hi,

I was thinking more along the lines of:

True positive: GeneA is associated with CancerB.
False positive: GeneA is not associated with CancerB.

Kind of like how the GAD and EU-ADR has true positive and false positive sentences.

Best,
KMS

**Comment by jakelever** [comment]
The [CancerMine corpus](https://github.com/jakelever/cancermine) might be the most relevant. It distinguishes whether a gene is associated as a driver, oncogene or tumor suppressor. There are positive and negative sentences in there.

**Comment by kmurphy902** [comment]
Ok—thanks!
