### ISSUE TITLE
Access to annotated sentences

### ISSUE THREAD

**Issue by swartchris8** [jakelever/civicmine#2]
I was wondering where I can find the 1500 annotated sentences used to train the model?

I would assume these are the sentences:  https://github.com/jakelever/cancermine/blob/master/data/cancermine_corpus.zip

**Comment by jakelever** [comment]
Yes, there are 1500 sets of files in BioNLP Shared Task standoff format. There's some info about the file format here: https://kindred.readthedocs.io/en/stable/fileformats.html.

**Comment by iCHAIT** [comment]
HI @jakelever 

I have a quick question regarding this. May I know if these sentences have been annotated manually by the experts?

I read the civicmine paper and came across the following mentioned in the Abstract - 

> To this end, a group of cancer genomics experts annotated biomarkers and their clinical associations discussed in 800 sentences and achieved good inter-annotator agreement

May I know of the corpus linked above by @swartchris8 is the one that contains these 800 sentences? And these sentences were manually annotated by experts?
