### ISSUE TITLE
Annotated Sentences in CivicMine

### ISSUE THREAD

**Issue by iCHAIT** [jakelever/civicmine#3]
HI @jakelever ,

I read the CivicMine paper and came across the following mentioned in the Abstract -

> To this end, a group of cancer genomics experts annotated biomarkers and their clinical associations discussed in 800 sentences and achieved good inter-annotator agreement

May I know if the corpus linked by @swartchris8 in #2 (https://github.com/jakelever/cancermine/blob/master/data/cancermine_corpus.zip) is the one that contains these 800 sentences? Were these sentences were manually annotated by experts?

If not can you point me to the corpus of these 800 manually annotated sentences?

**Comment by jakelever** [comment]
Hi, thanks for the question. I noticed some confusion in the README so fixed it and put in a link to the corpus. The 800 sentences for CIViCmine can be found in the [data/](https://github.com/jakelever/civicmine/tree/master/data) of this repo.

**Comment by iCHAIT** [comment]
Thank you @jakelever 👍
